export default {
  ACCOUNTING: 'Accounting',
  ARCHITECTURE: 'Architecture',
  ARTIFICIAL_INTELLIGENCE: 'Artificial Intelligence',
  AUTO: 'Auto',
  APP_DEVELOPMENT: 'App Development',
  ART: 'Art',
  AVIATION: 'Aviation',
  BOATING: 'Boating',
  BUSINESS_DEVELOPMENT: 'Business Development',
  COMMUNICATION: 'Communication',
  COMMUNITY_LIAISON: 'Community Liaison',
  CONSTRUCTION: 'Construction',
  CRAFT: 'Craft',
  CULINARY: 'Culinary',
  DATA_ANALYSIS: 'Data Analysis',
  DATABASE_MANAGEMENT: 'Database Management',
  DIVING: 'Diving',
  DRONE: 'Drone',
  ELECTRICITY: 'Electricity',
  ENGINEERING: 'Engineering',
  ENTREPRENEURSHIP: 'Entrepreneurship',
  FINANCE: 'Finance',
  FUNDRAISING: 'Fundraising',
  GAMING: 'Gaming',
  GRAPHIC_DESIGN: 'Graphic Design',
  HOSPITALITY: 'Hospitality',
  HUMAN_RESOURCES: 'Human Resources',
  INFORMATION_TECHNOLOGY: 'Information Technology',
  LANDSCAPE: 'Landscape',
  LEGAL: 'Legal',
  MANAGEMENT: 'Management',
  MARKETING: 'Marketing',
  MEDICAL: 'Medical',
  MUSICAL: 'Musical',
  PHOTOGRAPHY: 'Photography',
  PLUMBING: 'Plumbing',
  PUBLIC_RELATIONS: 'Public Relations',
  RENEWABLE_ENERGY: 'Renewable Energy ',
  RESEARCH: 'Research',
  SOCIAL_MEDIA: 'Social Media',
  STRATEGY_CONSULTING: 'Strategy Consulting',
  TAXI: 'Taxi',
  TRANSLATION: 'Translation',
  VETERINARY_SERVICES: 'Veterinary Services',
  VIDEOGRAPHY: 'Videography',
  WEB_DESIGN: 'Web Design',
  WEB_DEVELOPMENT: 'Web Development',
  WRITING: 'Writing',
}