export default {

    obBody: {
        flex: 1,
        backgroundColor: 'white',
        justifyContent: 'center'
    },
    obTextTopContainer: {
        borderColor: 'black',
        backgroundColor: '#00FF98',
        width: '20%',
        height: '10%',
        borderRadius: 50,
        justifyContent: 'center',
        alignItems: 'center',
        alignContent: 'center',
        marginLeft: '42.5%',
    },
    obTextTop: {
        color: '#000000',
        fontFamily: 'OpenSans-Regular',
        fontSize: 18,
        lineHeight: 25,
        marginLeft: '5%',
        marginTop: '3%',
        marginBottom: '7%',
        marginRight: '7%',  
    },
    obText: {
        color: '#000000',
        fontFamily: 'OpenSans-Regular',
        fontSize: 18,
        lineHeight: 25,
        marginLeft: '5%',
        marginTop: '2%',
        marginBottom: '2%',
        marginRight: '7%',      
    },
    obTitle: {
        color: '#000000',
        fontFamily: 'OpenSans-Bold',
        fontSize: 28,
        lineHeight: 38,
        marginLeft: '5%',
        marginTop: '18%',
        marginBottom: '2%',
        marginRight: '7%',
    },
    obSubtitle: {
        color: '#000000',
        fontFamily: 'OpenSans-Bold',
        fontSize: 21,
        lineHeight: 29,
        marginLeft: '5%',
        marginTop: '2%',
        marginBottom: '2%',
        marginRight: '7%',
    },
    obFwdContainer: {
        width: 112,
        height: 40,
        backgroundColor: '#00FF98',
        borderRadius: 20,
        alignSelf: 'flex-end',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        alignContent: 'center',
        marginRight: '5%',
    },
    obFwdBtnText: {
        fontFamily: 'OpenSans-Bold',
        fontStyle: 'normal',
        fontSize: 18,
        lineHeight: 25,
        color: '#000000',
    },
    obRectangle1: {
        position: 'absolute',
        width: 241,
        height: 241,
        left: 16,
        top: 433,
        backgroundColor: '#C4C4C4',
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: '#C4C4C4'
    },
    obRectangle2: {
        position: 'absolute',
        width: 241,
        height: 241,
        left: 94,
        top: 411,
        backgroundColor: '#C4C4C4',
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: '#00FF9D'
    },
    obFieldName: {
        fontFamily: 'OpenSans-Regular',
        fontSize: 14,
        lineHeight: 19,
        color: '#000000',
        marginLeft: '5%',
        marginTop: '3%'
    },
    obTextInput: {
        backgroundColor: 'white',
        borderRadius: 50,
        marginLeft: '5%',
        marginRight: '5%',
        marginBottom: '2%',
        marginTop: '2%',
        height: 50,
        paddingLeft: 20,
        fontFamily: 'OpenSans-Regular',
        fontSize: 14,
        color: '#000000',
        borderColor: '#DEDEDE',
        borderWidth: 0.5,
    },
    obTextInputBottom: {
        backgroundColor: 'white',
        borderRadius: 50,
        marginLeft: '5%',
        marginRight: '5%',
        marginBottom: '5%',
        marginTop: '2%',
        height: 50,
        paddingLeft: 20,
        fontFamily: 'OpenSans-Regular',
        borderColor: '#DEDEDE',
        borderWidth: 0.5,
    },
    obNumInput: {
        marginLeft: 20,
        marginBottom: 20,
        backgroundColor: 'rgba(196, 196, 196, 0.5)',
        borderRadius: 8,
        keyboardType: 'phone-pad'
    },
    obUploadBtn: {
        backgroundColor: '#00FF9D',
        borderRadius: 8
    },
    obOrgBtn: {
        backgroundColor: '#C4C4C4',
        borderRadius: 24,
        width: 214,
        height: 68
    }

}