export default {
	scrollBG        : {
		backgroundColor : '#E5E5E5',
		height          : '100%',
	},
	touchableView   : {
		backgroundColor : 'black',
		alignItems      : 'center',
		justifyContent  : 'center',
		borderRadius    : 5,
		height          : 35,
	},
	touchableText   : {
		color         : '#fff',
		textTransform : 'uppercase',
		fontWeight    : 'bold',
		letterSpacing : 2,
	},
	sections        : {
		marginTop       : 8,
		backgroundColor : '#fff',
		width           : '100%',
		marginLeft      : 8,
		marginRight     : 8,
		padding         : 25,
		borderRadius    : 5,
		fontSize        : 15,
	},
	title           : {
		fontSize   : 18,
		alignSelf  : 'center',
		marginLeft : 0,
		fontFamily : 'Lato-Bold',
	},
	iconWrap        : {
		flexWrap          : 'wrap',
		alignItems        : 'center',
		flexDirection     : 'row',
		borderBottomColor : '#eee',
		borderBottomWidth : 1,
		marginBottom      : 2,
		paddingBottom     : 20,
	},
	linkWrap        : {
		flexWrap      : 'wrap',
		alignItems    : 'center',
		flexDirection : 'row',
		marginLeft    : '7%',
	},
	linkText        : {
		fontSize   : 18,
		alignSelf  : 'center',
		marginLeft : '4%',
		fontFamily : 'Lato',
		marginTop  : '4%',
	},
	logoutButton    : {
		marginTop : '5%',
		width     : 40,
		height    : 40,
	},
	buttonContainer : {
		width           : '30%',
		height          : 30,
		marginTop       : 10,
		flexDirection   : 'column',
		flexWrap        : 'nowrap',
		marginLeft      : '35%',
		marginRight     : '35%',
		borderRadius    : 4,
		backgroundColor : '#00FF9D',
		justifyContent  : 'center',
	},
	buttonText      : {
		fontFamily     : 'Lato-Bold',
		letterSpacing  : 0.8,
		textAlign      : 'center',
		color          : 'black',
		justifyContent : 'center',
		alignItems     : 'center',
		fontSize       : 16,
	},
};
