export default {
  sectionContainer: {
    flexDirection: 'column',
    flexWrap: 'wrap',
    paddingLeft: '3%',
    paddingRight: '3%',
    flex: 1,
    alignItems: 'center',
  },
  Card: {
    marginTop: 20,
    backgroundColor: '#fff',
    width: '100%',
    padding: 25,
    borderRadius: 10,
  },
  inputContain: {
    borderWidth: 2,
    borderColor: '#C4C4C4',
    padding: 5,
    borderRadius: 3,
    width: '100%',
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  inputText: {
    fontSize: 22,
  },
  touchableButton: {
    marginBottom: 100,
    paddingTop: 25,
    paddingBottom: 25,
    width: '100%',
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  touchableView: {
    width: 282,
    height: 55,
    borderRadius: 20,
    backgroundColor: '#00FF9D',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
  },
  touchableText: {
    fontFamily: 'Lato-Bold',
    letterSpacing: 2,
    fontStyle: 'normal',
    fontSize: 18,
    lineHeight: 25,
    color: '#000000',
  },
  textContainer: {
    marginBottom: '5%',
  },
  obText: {
    color: '#000000',
    fontFamily: 'Lato',
    fontSize: 18,
    lineHeight: 25,
    marginLeft: '5%',
    marginTop: '2%',
    marginBottom: '2%',
    marginRight: '7%',
  },
  obTitle: {
    color: '#000000',
    fontFamily: 'Lato-Bold',
    fontSize: 26,
    lineHeight: 22,
    marginLeft: '5%',
    marginBottom: '2%',
    marginTop: '5%',
    marginRight: '5%',
    flexWrap: 'wrap',
    flexDirection: 'row',
    flex: 1,
    textAlign: 'center',
  },
  obSubTitle: {
    color: '#000000',
    fontFamily: 'Lato',
    fontSize: 22,
    lineHeight: 22,
    marginLeft: '5%',
    marginBottom: '2%',
    marginTop: '10%',
    marginRight: '5%',
    flexWrap: 'wrap',
    flexDirection: 'row',
    flex: 1,
    textAlign: 'center',
  },
  obBody: {
    flex: 1,
    justifyContent: 'center',
    marginTop: '10%',
  },
  obFwdContainer: {
    width: 282,
    height: 50,
    borderWidth: 2,
    borderColor: '#000',
    borderRadius: 20,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  obFwdBtnText: {
    fontFamily: 'Lato-Bold',
    fontStyle: 'normal',
    letterSpacing: 2,
    fontSize: 18,
    lineHeight: 25,
    color: '#000000',
  },
};
